.TH "Svg2Pdf documentation" 1 "14 Jun 2019" "User Manual"

.SH NAME
svg2pdf

.SH DESCRIPTION
Improved svg2pdf example.

.SH SYNOPSIS
svg2pdf input_file.svg output_file.pdf [dpi=0.0]

.SH COPYRIGHT
Copyright 2012 Mailson Lira.
 All rights reserved.

.SH SEE ALSO
 rsvg-convert(1)

.SH CONTACTS
 Website: https://github.com/omailson/svg2pdf
 Author: Mailson Lira <omailson@github.com>
 Country: Recife, PE, Brazil
 Date: 2012-03-09
